### ISSUE TITLE
problem about your packages

### ISSUE THREAD

**Issue by 0-KaiKai-0** [zyxxmu/cam#1]
I got the following error when running generate_task_data.py for QA tasks in your Step 1:

I setup the enviroment as your instructions. Did I miss any package?

> from tasks import EvalHarnessAdaptor
> ModuleNotFoundError: No module named 'tasks'

**Comment by duyuxuan1486** [comment]
I‘m sorry for forgetting to upload the "tasks" folder, which caused your problem. The folder has now been uploaded under "cam/cam_hf/tasks".

**Comment by 0-KaiKai-0** [comment]
Thank you for your reply!

I got a new error when running generate_task_data.py for QA tasks in your Step 1:

> Traceback (most recent call last):
  File "/home/jskai/workspace/cam/cam_hf/generate_task_data.py", line 57, in <module>
    results = evaluator.evaluate(adaptor, tasks.get_task_dict([args.task_name
  File "/home/jskai/anaconda3/envs/cam/lib/python3.9/site-packages/lm_eval/tasks/__init__.py", line 317, in get_task_dict
    task_name_dict = {
  File "/home/jskai/anaconda3/envs/cam/lib/python3.9/site-packages/lm_eval/tasks/__init__.py", line 318, in <dictcomp>
    task_name: get_task(task_name)()
  File "/home/jskai/anaconda3/envs/cam/lib/python3.9/site-packages/lm_eval/base.py", line 412, in __init__
    self.download(data_dir, cache_dir, download_mode)
  File "/home/jskai/anaconda3/envs/cam/lib/python3.9/site-packages/lm_eval/base.py", line 441, in download
    self.dataset = datasets.load_dataset(
  File "/home/jskai/anaconda3/envs/cam/lib/python3.9/site-packages/datasets/load.py", line 1670, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/jskai/anaconda3/envs/cam/lib/python3.9/site-packages/datasets/load.py", line 1447, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/jskai/anaconda3/envs/cam/lib/python3.9/site-packages/datasets/load.py", line 1172, in dataset_module_factory
    raise e1 from None
  File "/home/jskai/anaconda3/envs/cam/lib/python3.9/site-packages/datasets/load.py", line 1151, in dataset_module_factory
    return HubDatasetModuleFactoryWithoutScript(
  File "/home/jskai/anaconda3/envs/cam/lib/python3.9/site-packages/datasets/load.py", line 744, in __init__
    assert self.name.count("/") == 1
AssertionError

**Comment by duyuxuan1486** [comment]
Which version is your "datasets" and "lm_eval" library? It can run under datasets==2.15.0 and lm_eval==0.3.0

**Comment by 0-KaiKai-0** [comment]
It is due to my GPU problem. It works now. Thank you!
